Add AppIndicator/SysTray icon
zocker-160/thinkfan-ui pull request #4
Opened 2023-01-11 07:16 UTC by blipk

Hey thanks for this wrapper around the thinkfan fan control, it works great and I use it a lot.

I was finding that it was a bit much having the window open all the time though, so I set up a `QSystemTrayIcon` on my panel like so:

![image](https://user-images.githubusercontent.com/45532845/211740712-9116a0e9-d600-41f1-a899-a5b9e0aef082.png)

Clicking any of the temp or fan readings will open up your main UI, or fan speeds can be set from the indicators menu without opening the main UI.

Could possibly add a couple of command line arguments to run in either mode if you would prefer.

Let me know if there's anything you want changed to get this merged.

2023-01-11 17:13 UTC, zocker-160 commented
Thank you very much for this, I will take a look.

> I'm not sure how to assign anyone or if you have a PR process here

All good, since this is a very small project, I don't really have any PR process set up, I actually never expected a PR xD.

> I also added in so it makes a call to pkexec to prompt for sudo password if it's needed for setting the fan speed.
This is useful as I wasn't able to run it as root without a terminal due to missing QT env arrangements.

So does the [start script](https://github.com/zocker-160/thinkfan-ui/blob/master/linux_packaging/assets/thinkfan-ui) not work properly?

This part is kinda tricky and I am using the same script that is also used for gparted and timeshift and in my testing it did work, although the theming did break during my testing.

2023-01-11 17:54 UTC, zocker-160 requested changes
review done, few suggestions and one blocker

2023-01-11 17:54 UTC, zocker-160 commented on src/ui/systray.py
> +        if fan_speed and "Fan RPM" in actions:
blocker: 
this causes crash with `UnboundLocalError: local variable 'fan_speed' referenced before assignment` when line 79 returns false.

This is the case if the ThinkPad does not have the thinkpad_acpi module installed and it should not crash in that case.

2023-01-11 17:54 UTC, zocker-160 commented on src/ui/systray.py
> +        if fan_level and "Fan Level" in actions:
blocker: 
same as above in case line 77 is false

2023-01-11 17:54 UTC, zocker-160 commented on src/fan.py
> +        self.setApplicationVersion(VERSION)
suggestion:
I would suggest adding
```py
        self.setApplicationName("ThinkFan UI")
        self.setApplicationDisplayName("ThinkFan UI")
```
as otherwise the application will be shown as `fan.py` in the notification area on KDE (missing icon is unrelated):
![Screenshot_20230111_183525](https://user-images.githubusercontent.com/36563538/211877820-9eee465d-f772-4999-8551-0b5e37e5e84c.png)

2023-01-11 17:54 UTC, zocker-160 commented on src/ui/systray.py
> +        self.icon.show()
suggestion:
I think it would make sense to add 
```py
self.icon.activated.connect(self.mainWindow.appear)
```
here in between, because on KDE it does differentiate between a right click and a left click on the try icon.

Left click will trigger the `activated()` signal, while right click will open the menu. On GNOME it always acts like a left click, so there this signal will never be triggered.

2023-01-11 17:54 UTC, zocker-160 commented on src/fan.py
> +        self.center()
suggestion:
I very much dislike this, as it will always move the window to the center of the screen even if it is already visible.

It is annoying in case I move the window to a custom location and then trigger the activate by accident or in case an error happens.

Furthermore this command does nothing on Wayland, so I would suggest removing this line.

2023-01-11 21:46 UTC, blipk commented on src/ui/systray.py
> +        self.icon.show()
Thanks, I use GNOME so I wasn't aware of this difference.
Double clicking the icon on GNOME seems to activate that signal, will add this in.

2023-01-11 21:47 UTC, blipk commented on src/fan.py
> +        self.center()
No worries, in my testing, I found that your center() function did work fine on my Wayland session.

I'm not sure window position is remembered for me in any case though.

Will change to take .center() out of appear()

2023-01-11 21:52 UTC, blipk commented
Thanks @zocker-160 have pushed change to fix those review items.

As for the runscript, I get the following QT error:
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

/usr/bin/thinkfan-ui: line 30: 89977 Aborted                 (core dumped) ${app_command}
```

If I run it with sudo rather than pkexec it works fine, but then I have to have that sudo terminal section active somewhere.

2023-01-12 09:23 UTC, zocker-160 commented on src/fan.py
> +        self.center()
> No worries, in my testing, I found that your center() function did work fine on my Wayland session.

Ok that is interesting, because that did not work for me.

I will do some further testing on this, because centering will have to be called at least once, but it should not be called when the window is already visible. 
This is not a blocker though, since I will have to test a bit more to understand how it behaves.

2023-01-12 09:36 UTC, zocker-160 commented
> As for the runscript, I get the following QT error:

Ok weird, it did work just fine for me, but that being said, there seems to be another issue that I just noticed.

When running the entire application as root (using sudo), the tray icon does not show up. Does it work for you?
I feel like we are hitting the limit of the current implementation unless there is a way to change the permission requirements for `/proc/acpi/ibm/fan`.

2023-01-12 09:44 UTC, zocker-160 commented on src/ui/systray.py
> +        self.icon.show()
> Double clicking the icon on GNOME seems to activate that signal, will add this in.

good to know

2023-01-12 09:48 UTC, zocker-160 approved these changes
I am willing to merge this, although the sudo issue will require a solution before I can push a new version out, as it currently will neither show a window nor the tray icon.

2023-01-12 10:08 UTC, zocker-160 commented
Thank you very much!

2023-01-12 10:08 UTC, merged

2023-01-12 11:42 UTC, blipk commented
No worries @zocker-160 

The indicator does work for me on GNOME with sudo, but it has different styling.
Perhaps a QT env issue on your end? I had to mess around with kvantum theme manager at one point

2023-01-12 11:54 UTC, zocker-160 commented
>  Perhaps a QT env issue on your end? I had to mess around with kvantum theme manager at one point

Yes probably, but I will avoid this environment variable dance by just running the application as user. 

> EDIT: Changing the permissions on that endpoint work for me too, weird as it didn't last time I tried.
Maybe just changing the permissions on that file once with pkexec when excepting the PermissionError?

Yep that is exactly what I am going to do and then I can also get rid of the sudo and pkexec fiddling in the start script.

2023-01-14 03:28 UTC, blipk commented
no worries @zocker-160 

I just added changed the command when excepting the `PermissionError` to:
```python
cmd = [f"""pkexec python -c \"import os; os.chmod('{PROC_FAN}', 0o777)
with open('{PROC_FAN}', 'w+') as soc: soc.write('level {speed}')\""""]
```
See - https://github.com/zocker-160/thinkfan-ui/compare/master...blipk:thinkfan-ui:master


This works well as I found that the file permissions where getting reset by something any time I rebooted.

2023-01-14 12:31 UTC, zocker-160 commented
> This works well as I found that the file permissions where getting reset by something any time I rebooted.

this case should be covered by https://github.com/zocker-160/thinkfan-ui/blob/914e160c3a5043e86419a8b7669b28b3a0ee030f/src/fan.py#L52